hot-fix (client/landing) : titulo del landing
LMCT04/TestGroup pull request #1
Opened 2023-06-01 15:48 UTC by LMCT04

revisen esto bobos

2023-06-01 15:50 UTC, FerLorenzoR commented on client/src/components/views/landingPage/landing.jsx
> +                <h1 className={style.title} > WELCOME TO MY DOG APO </h1>
Me parece alta boludes, cambia eso

2023-06-01 15:52 UTC, Juan9999K reviewed
Comentarios

2023-06-01 15:52 UTC, julianllop commented
Comentario de prueba?

2023-06-01 15:53 UTC, julianllop commented on client/src/components/views/landingPage/landing.jsx
>                  <p className={style.p} >
este p esta perfectisimo

2023-06-01 15:53 UTC, FerLorenzoR commented
Doble probando

2023-06-01 15:54 UTC, LMCT04 commented
rrrrrr`rr`

2023-06-01 15:55 UTC, FerLorenzoR requested changes
Me parece una falta de respeto la forma en la que codeas!

2023-06-01 15:56 UTC, DUVANCRUZ reviewed
esta bien

2023-06-02 15:13 UTC, juancjerezm approved these changes
Aprobado

2023-06-02 15:42 UTC, closed without merging